name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: windows-latest
    env:
      NuGetPackageSourceCredentials_SceneGalleryGitHub: "Username=${{ github.actor }};Password=${{ secrets.GITHUB_TOKEN }}"

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "ga"

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test SceneGallery.Plugin.PixivAuthors.Tests/SceneGallery.Plugin.PixivAuthors.Tests.csproj -c Release -p:DeployPluginToApp=false
